### PR TITLE
Code_of_Conduct and Contributing files added

### LINKED ISSUE #40: Adding Code of Conduct.md & CONTRIBUTING.md
There is no Code of Conduct as of now. I have mentioned in one of the points in readme regarding it.
So can I make a file named Code of Conduct ?

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fixes #40 

Files added:
- [x] Code_of_Conduct.md
- [x] Contributing.md

Comment:
2 new files added with content

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@plxity Label is not added in this because of which my score is not updated, Kindly check

**Comment by plxity** [comment]
@shreyakapoor08 You have not linked these files in the Readme.md. Please link them. Closing this PR. Please raise a new PR.

**Comment by shreyakapoor08** [comment]
Got it, will just do that, thanks

**Comment by shreyakapoor08** [comment]
@plxity @yellowwoods12 Kindly add labels to it, I am not able to see my updated score :)

**Comment by shreyakapoor08** [comment]
Thanks @plxity 😊

**Pull request merged**
