### PR TITLE
Implementation for global pincodes

### LINKED ISSUE #2: As of now this module works only for Indian Pinocdes. Implement it for global pincodes.

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #2 

@plxity here's what the PR offers:

As discussed since the only way to achieve this would be via offline data set, I have implemented the same version in React demonstrated [here](https://vigorous-rosalind-53c7e6.netlify.com/ ).

As discussed right now the data set only includes for India and US zip codes and so it'll work only for that.

The issue about the bundle size optimization is addressed via an API as you suggested, the API not not built extremely robust it's just enough to be up and running and I have used the same to minimize bundle size. 

Here's a small example for it's working:
React App

Future Improvements which can be done:
- Improving the API
- Improving the dataset (For India it works extremely well so it can be avoided )
- The additional input to add states, so seperate json files can be kept instead of having on huge file

### CODE REVIEW

**Comment by yellowwoods12** [comment]
@abhu-A-J We need to remove multiple similar fields when one types a pincode. Like I can see multiple "Pune" in the city dropdown and similarly in state.

**Comment by yellowwoods12** [comment]
@plxity Also lets keep this to a separate testing branch since it is a completely different development for the module. We'll also encourage participants to work on the possible improvements to this PR by other participants.

**Comment by abhu-A-J** [comment]
> @abhu-A-J We need to remove multiple similar fields when one types a pincode. Like I can see multiple "Pune" in the city dropdown and similarly in state.

@yellowwoods12 The repetition is due to the dataset itself. It's because the dataset has similar fields, if we use a dataset that has no repetition then that issue won't be present.

**Comment by plxity** [comment]
@abhu-A-J You can remove duplicate fields in this too. Please make those changes then we are going to merge this PR.

> @plxity Also let's keep this to a separate testing branch since it is a completely different development for the module. We'll also encourage other participants to work on the possible improvements to this PR.

Yes, definitely.

**Comment by plxity** [comment]
@abhu-A-J You can remove duplicate fields in this too. Please make those changes then we are going to merge this PR.

**Comment by abhu-A-J** [comment]
> @abhu-A-J You can remove duplicate fields in this too. Please make those changes then we are going to merge this PR.

@plxity The duplicate data fields are present because the dataset itself has duplicate field. If we can get the data set with non-repetitive fields, this issue won't be present. It's not a side effect from code.

**Comment by yellowwoods12** [comment]
@abhu-A-J Yes we get that. What we are suggesting here is to filter out duplicate entries after you've fetched them from the API.

**Comment by abhu-A-J** [comment]
@yellowwoods12 Ma'am I have removed the problem for repetitive data. Here is the working now.
Hope it's okay now??

React App

**Comment by plxity** [comment]
@abhu-A-J Can you raise this PR to the development branch?

**Comment by abhu-A-J** [comment]
> @abhu-A-J Can you raise this PR to the development branch?

Sure, I'll do the same, so I'm closing this PR and make a new PR to development branch.

**Pull request closed without merging**
