### PR TITLE
feat: new field district

### LINKED ISSUE #42: feat: add places for better accuracy
Currently, the `city` field displays `district` data from API end-point, which is inaccurate.
From the API end-point, we can add more fields-

`Field : Parameter`
------------------------
`Town/City : name`
`District : district`
`State : state`

Where `field` is the displayed data and `parameter` are data from API.

### PR DESCRIPTION
**Pull request by adityabisoi**
Closes #42 

District field added, along with improvements to the `City` field, which previously showed district from API.

@plxity @yellowwoods12 please review?

### CODE REVIEW

**Comment by adityabisoi** [comment]
@AdityaSrivast should I include the demo as pictures in the README ?

**Comment by AdityaSrivast** [comment]
@adityabisoi Yes, We should update that too. Also please provide a demo link(codepen, fiddle) for verifying your implementation.

**Comment by adityabisoi** [comment]
@AdityaSrivast I have updated the README. Here is a sandbox implementation: https://codesandbox.io/s/festive-platform-n1nk1

**Comment by adityabisoi** [comment]
@AdityaSrivast I have made all the necessary changes. Please review.

**Comment by plxity** [comment]
@adityabisoi Did you make changes in the codepen implementation?

**Comment by adityabisoi** [comment]
@plxity No, I needed a confirmation first, as asked above. Should I change it?

**Comment by yellowwoods12** [comment]
> @plxity No, I needed a confirmation first, as asked above. Should I change it?

Yes go ahead and make changes in the codepen implementation.

**Comment by adityabisoi** [comment]
@yellowwoods12 Codepen updated!

**Pull request merged**
