### PR TITLE
Added Css to Input Fields for react-pincode

### LINKED ISSUE #4: Improve CSS of all the input fields.

### PR DESCRIPTION
**Pull request by habeeba-naaz**
Please let me know any changes to be done..
Fixes #4

### CODE REVIEW

**Comment by habeeba-naaz** [comment]
How to access through module those properties..please provide examples ?

**Comment by yellowwoods12** [comment]
@habeeba-naaz  make changes to App.css inside src folder of the project and not inside test-server.

**Comment by habeeba-naaz** [comment]
Yes...I understood...but how to access those properties...please provide examples

**Comment by yellowwoods12** [comment]
@habeeba-naaz  that's the task ;)

**Comment by habeeba-naaz** [comment]
Okay...sure..i'll figure it out

**Comment by plxity** [comment]
@habeeba-naaz Any updates?

**Comment by habeeba-naaz** [comment]
Whatever styles I applied in app.css it’s not reflecting on web page ?

**Comment by habeeba-naaz** [comment]
I made changes in module itself and npm started from test-server...am I right?

**Comment by yellowwoods12** [comment]
@habeeba-naaz  After making the changes in the module you've to rum npm run build and then restart the test-server

**Comment by habeeba-naaz** [comment]
Npm run build-from module itself I should run?

**Comment by yellowwoods12** [comment]
@habeeba-naaz  what is the status here?

**Comment by habeeba-naaz** [comment]
I know how to style but unable to access properties and style...I tried non run build it’s working...please provide one example I can do it

**Comment by habeeba-naaz** [comment]
Sorry...I am not getting how to solve this issue..please unassign me from this issue and give this to someone who wants to do

**Comment by AdityaSrivast** [comment]
Alright @habeeba-naaz closing this PR.

**Pull request closed without merging**
