### PR TITLE
ZIP Validation,Message Display & API Fetch Parameters Fixed

### LINKED ISSUE #5: Improve error handling functionality when pincode is not correct.

### LINKED ISSUE #23: Create a validation check for pincodes
As of now, when a wrong pincode is entered the input field turns red. There is no type check for various kind of wrong inpiuts. For example, a pincode must be of 6 digits. So if some number less than or greater than that is entered an alert should display.
Similarly if alphabets are entered then a specific alert should display for it as well and so on.

### LINKED ISSUE #26: Changes in the data retrieved for the API used in the project.
Currently, the project is using the "Region" parameter of the response to fill the City field. The results will be more accurate if instead of "Region", the "District" parameter is used.

### PR DESCRIPTION
**Pull request by Xtremilicious**
Fixed #23 and Fixed #26 and Fixed #5 

I have got a working prototype:
ScreenShot_20200306124608

1. User can ONLY input numbers, and a proper message is displayed if the number of digits is not 6.
2. API Fetch Parameter changed from "Region" to "District" as it is more accurate.

### CODE REVIEW

**Comment by yellowwoods12** [comment]
Hey @Xtremilicious, it looks good but it will be great if you can generate a prompted alert everytime a user enters an invalid pincode. It looks better from UI perspective of things.

**Comment by Xtremilicious** [comment]
> Hey @Xtremilicious, it looks good but it will be great if you can generate a prompted alert everytime a user enters an invalid pincode. It looks better from UI perspective of things.

It could have been done but some users may not like an alert or a modal popping out, since it may affect the UI/UX of the app in which it is being used. So I kept it as simple as possible. 

What can be done is add a styling property/parameter which can be passed while using the <Pincode> to style the error message being displayed so that the user can style it accordingly. Let me know your suggestions:)

**Comment by plxity** [comment]
@Xtremilicious Please make individual PR for each issue.

**Comment by Xtremilicious** [comment]
> @Xtremilicious Please make individual PR for each issue.

What if I fixed all the 3 issues in one commit?

**Pull request closed without merging**
