### PR TITLE
Validation check for Pincodes

### LINKED ISSUE #23: Create a validation check for pincodes
As of now, when a wrong pincode is entered the input field turns red. There is no type check for various kind of wrong inpiuts. For example, a pincode must be of 6 digits. So if some number less than or greater than that is entered an alert should display.
Similarly if alphabets are entered then a specific alert should display for it as well and so on.

### PR DESCRIPTION
**Pull request by Xtremilicious**
Fixed #23  

I have got a working prototype:
1. User can ONLY input numbers, and a proper message is displayed if the number of digits is not 6.
2. API Fetch Parameter changed from "Region" to "District" as it is more accurate.

ScreenShot_20200307001833
ScreenShot_20200307001839
ScreenShot_20200307001910

Kindly guide me since this solution fixes the problem for 3 issues, and @plxity asked me to open a PR for each issue.

### CODE REVIEW

**Comment by plxity** [comment]
@Xtremilicious can you please remove package-lock.json? and add a screenshot of the changes you made.
Thanks,

**Comment by Xtremilicious** [comment]
> @Xtremilicious can you please remove package-lock.json? and add a screenshot of the changes you made.
> Thanks,

Sure, on it.

**Comment by plxity** [comment]
> > @Xtremilicious can you please remove package-lock.json? and add a screenshot of the changes you made.
> > Thanks,
> 
> Sure, on it.

And also remove build file. We will build a file later.

**Comment by Xtremilicious** [comment]
@plxity done:)

**Comment by plxity** [comment]
@Xtremilicious It still has package-lock.json in test-server folder. Please remove it.

**Comment by Xtremilicious** [comment]
> @Xtremilicious It still has package-lock.json in test-server folder. Please remove it.

@plxity done.

**Comment by plxity** [comment]
@Xtremilicious You have removed the original build file. Don't do that. 
KIndly make the changes.

**Comment by Xtremilicious** [comment]
@plxity done.

**Comment by plxity** [comment]
LGTM :+1:

**Comment by Xtremilicious** [comment]
@plxity @arpit9667  Kindly add a label 'gssoc20' and the appropriate difficulty level for it to add to my score at GSSoC Leaderboard. Thanks :)

**Note:** This PR fixed three issues of 2 easy and 1 medium difficulty, so the difficulty of this PR should be 'hard' so that I can get the collective points. Thanks.

**Comment by Xtremilicious** [comment]
@yellowwoods12 actually this PR solved **three** issues namely #23 #26 and #5 
#23 was of **medium** difficulty.
#26 was of **easy** difficulty
#5 was of **medium** difficulty

GSSoC provides separate points for each difficulty level. So kindly let me know how I can get all the points.

**Comment by Xtremilicious** [comment]
@plxity @yellowwoods12 Sorry for pinging again and again, but I just want to label 'hard' to be assigned to this pull request instead of 'medium' since this covers 3 issues, 2 medium and 1 easy, so a total of 4+7+7 = 18 points. Kindly give me the 'hard' tag along with 'medium' tag so that I can get at least 10+7=17 points. Thanks.

**Pull request merged**
