### PR TITLE
Update README.md. Fixing issue #7

### PR DESCRIPTION
**Pull request by siddhishree**
add the link for codepen implementation.

### CODE REVIEW

**Comment by plxity** [comment]
@siddhishree you haven't included one of the CSS classes. Please make the changes.

**Comment by siddhishree** [comment]
Done. @plxity

**Comment by plxity** [comment]
LGTM :+1:

**Comment by siddhishree** [comment]
@plxity Please add gssoc20 and difficulty level here too, so that scores can get counted. I asked GS and they asked me to let you know that labels have to be added on the merged PR too.

**Pull request merged**
